spring.datasource:
  url: jdbc:mysql://localhost/kotlin_api?createDatabaseIfNotExist=true
  username: root
  password: kotlinbackend


spring.mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update

jwt:
  secret: f74cb217-8bd2-4a48-b58c-e7e971c8480e
  expiration: 300000