spring.datasource:
  url: jdbc:mysql://localhost/kotlin_api?createDatabaseIfNotExist=true
  username: root
  password: kotlinbackend


spring.mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update